// test06.js
process.on('uncaughtException', (err) => {

});